apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example-obs2 
spec:
  selector:
    matchLabels:
      app: app-example-obs2
  template:
    metadata:
      labels:
        app: app-example-obs2
    spec:
      containers:
        - image: okteto.dev/java-gradle-app-example-obs2:1.0.0
          name: app-example-obs2

---

apiVersion: v1
kind: Service
metadata:
  name: app-example-obs2
spec:
  type: ClusterIP
  ports:
    - name: "app-example-obs2"
      port: 8080
  selector:
    app: app-example-obs2

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-example-obs2
  annotations:
    dev.okteto.com/generate-host: app-example-obs2
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: app-example-obs2
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific